spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_db
    platform: postgres
    username: tester
    password: tester
  main:
    allow-bean-definition-overriding: true